#!/bin/sh
OPENHIM_CONFIG=/etc/openhim/config.json
TMP_CONFIG=/tmp/openhim-config.json

# Stop openhim-core
stop openhim-core

# Use jq to insert correct api https port
jq '.api.httpsPort = 5008' $OPEHIM_CONFIG > $TMP_CONFIG
mv $TMP_CONFIG $OPENHIM_CONFIG

# Start openhim-core
start openhim-core
